@startuml diabgrama

Fornecedor --|> Usuario
Cliente --|> Usuario
Catalogo --* Iten
TicketTransação --|> Ticket

Usuario --> Ticket

Fornecedor "1..*" - "1..1" Catalogo
(Fornecedor, Catalogo) ... Transação
(Fornecedor, Cliente) ... Chat
Transação "0..1" - "1..1"  TicketTransação

class Transação{
    Status
    Data
    Conversar()
    Cancelar()
}

class Usuario {
  + email
  + senha
  + nome
  + sobre_nome
  + data_nascimento
}

class Fornecedor {
  + pontuação
  + Catalogo<ItensPublicados>
  + Lista<Seguidores>
}

class Cliente {
  + pontuação
  + Lista<FornecedoresFavoritos>
}

class Iten {
   + titulo
   + condiçõe_de_uso
   + troca_ou_venda
   + valor_venda
   + descição
   + List<Imagen> 
}

class Catalogo {
  + List<Iten>
}

class Ticket {
  + Usuario_Solicitante
  + Usuario_Reportado
  + Motivo_do_Reporte
  + Transação
  + Anuncio

}

class TicketTransação{
  + Identificador
  + Status
  + Mediador
  + Solução
  + Tramites
}

@enduml

